### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by Splinxyy** [Splinxyy/CommunityTextBasedPokemon#9]
@MarcusTalbotNL 

I would like to ask your thoughts behind the active Pokemon Map.

Would this need to be changed from 6 to 5 now, as we are using 0?

Because if you were going to use values 1-6 (map size is 6), now that we are using 0-5 it would make sense to change the map size to 5.

**Comment by MarcusTalbotNL** [comment]
Nope, my original explanation was all wrong. Sorry 'bout that. What a Map does, is it takes two arguments, in this case, we have Map<Integer, Pokemon>, so it takes an Integer and a Pokemon as arguments. The Integer is used as the key to retrieve the value associated with it. The given Integer, can be any valid Integer, not necessarily values between 0-5 or 1-6. The size should always be 6, since a player can hold a maximum of 6 pokemon at a time. 

This makes the Map interface, and the HashMap class very powerful tools for storing data. You can find some more (and clear) info in the documentation on the Oracle site.

So, my recommendation is to keep the size on 6.

**Comment by Splinxyy** [comment]
I think we should lower the size to 5. I know how a map works.

Take a lookie:

0 --> First Pokemon
1 --> Second Pokemon
2 --> Third Pokemon 
3 --> Fourth Pokemon
4 --> Fifth Pokemon
5 --> Sixth Pokemon

And my reasoning for that is that you were going to do 1-6 with a map size of 6. That would include part 6 of the map. So logically, unless you did it wrong, my method works.

**Comment by MarcusTalbotNL** [comment]
The size is in now way related to the maximum Integer you can assign as key. We need a size of 6, as we have 6 elements in the map.

**Comment by Splinxyy** [comment]
Oh, the 6 includes the 0? So putting 6 is using 0,1,2,3,4,5?

**Comment by MarcusTalbotNL** [comment]
6 is only a representation of the expected amount of elements that will populate the map. So, if you use 0-5 as keys, that would be six elements, meaning that the expected size would be six elements.

**Comment by Splinxyy** [comment]
Gotcha. You can hypothetically use 111-116 and it would still fit. I was under the impression that it had to be 0-6, my bad.

**Comment by MarcusTalbotNL** [comment]
Yeah, exactly. That's what makes the Map such a powerful tool. Glad we figured that out!
